# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10.19.0

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
cache:
  paths:
  - node_modules/

stages:
  - dependencies
  - test
  - build
  - deploy

dependencies:
  stage: dependencies
  script:
  - echo "installing npm dependencies"
  - npm install
  - npm -v
  - echo "installing Mocha tests"
  - npm install --save-dev mocha 

test:
  stage: test
  script:
    - echo "test"
    - npm run test

deploy_staging:
  stage: deploy
  before_script:
    # Setup SSH deploy key
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'  
  environment:
    name: staging
    url: $DEPLOY_SERVER
  script:
    - ssh ubuntu@$DEPLOY_SERVER "sh /home/ubuntu/deploy/gitlabcicdnodejs.sh"
  only:
    - main
