POST localhost:3000/tramites
Content-Type: application/json

{
    "solicitante_id": 2,
    "tipo_vehiculo": 1,
    "placa": "MMV11E",
    "modelo": 1994,
    "organismo_transito_id": 1,
    "direccion_solicitante": "Cl 44322 1122",
    "cedula_comprador": "1133444",
    "cedula_vendedor": "1212111",
    "estado_id": 1,
    "observaciones": "Esto es un trámite de prueba"
}